<?php
/*
Plugin Name: EcoPower Tracker
Description: Calculates and displays the total power generated by wind and solar plants in real-time, along with the carbon offset generated. Features detailed input forms for plant data, real-time calculations, multiple data display options using shortcodes, and supports data import/export through CSV files.
Version: 1.4e
Author: Saqib Jawaid
License: GPL-3.0-or-later
*/

if ( ! defined( 'ABSPATH' ) ) {
    exit; // Exit if accessed directly
}

// Includes
require_once plugin_dir_path( __FILE__ ) . 'includes/sanitization.php';
require_once plugin_dir_path( __FILE__ ) . 'includes/settings.php';

// Admin Menu
function ecopower_tracker_admin_menu() {
    add_menu_page(
        'EcoPower Tracker',
        'EcoPower Tracker',
        'manage_options',
        'ecopower-tracker',
        'ecopower_tracker_admin_page',
        'dashicons-admin-generic',
        6
    );

    add_submenu_page(
        'ecopower-tracker',
        'Project Data',
        'Project Data',
        'manage_options',
        'ecopower-tracker-data',
        'ecopower_tracker_project_data_page'
    );
}
add_action( 'admin_menu', 'ecopower_tracker_admin_menu' );

// Admin Page
function ecopower_tracker_admin_page() {
    if (isset($_POST['upload_csv'])) {
        ecopower_tracker_handle_csv_upload();
    }
    if (isset($_POST['add_project'])) {
        ecopower_tracker_add_project();
    }
    include plugin_dir_path( __FILE__ ) . 'form.php';
}

// Project Data Page
function ecopower_tracker_project_data_page() {
    include plugin_dir_path( __FILE__ ) . 'data.php';
}

// Handle CSV upload
function ecopower_tracker_handle_csv_upload() {
    if (!empty($_FILES['csv_file']['tmp_name'])) {
        $csv = array_map('str_getcsv', file($_FILES['csv_file']['tmp_name']));
        $header = array_shift($csv);
        $projects = get_option('ecopower_projects', []);
        foreach ($csv as $row) {
            if(count($header) == count($row)) {
                $projects[] = array_combine($header, $row);
            }
        }
        update_option('ecopower_projects', $projects);
    }
}

// Add project manually
function ecopower_tracker_add_project() {
    $project = [
        'Project Company' => sanitize_text_field($_POST['project_company']),
        'Project Name' => sanitize_text_field($_POST['project_name']),
        'Project Location' => sanitize_text_field($_POST['project_location']),
        'Type of Plant' => sanitize_text_field($_POST['type_of_plant']),
        'Project CUF' => floatval($_POST['project_cuf']),
        'Generation Capacity (KW)' => intval($_POST['generation_capacity']),
        'Date of Activation' => sanitize_text_field($_POST['date_of_activation']),
    ];

    $projects = get_option('ecopower_projects', []);
    $projects[] = $project;
    update_option('ecopower_projects', $projects);
}

// Shortcode
function ecopower_tracker_shortcode() {
    ob_start();
    include plugin_dir_path( __FILE__ ) . 'shortcode.php';
    return ob_get_clean();
}
add_shortcode( 'ecopower_tracker', 'ecopower_tracker_shortcode' );

// Enqueue scripts and styles
function ecopower_tracker_enqueue_scripts() {
    wp_enqueue_style( 'ecopower-tracker-css', plugins_url( 'assets/style.css', __FILE__ ) );
    wp_enqueue_script( 'ecopower-tracker-js', plugins_url( 'assets/script.js', __FILE__ ), array('jquery'), null, true );
}
add_action( 'admin_enqueue_scripts', 'ecopower_tracker_enqueue_scripts' );
?>
