<?php
/**
 * Plugin Name: EcoPower Tracker
 * Description: Calculates and displays total power generated by wind and solar plants in real-time, along with the carbon offset generated.
 * Version: 1.1
 * Author: Saqib Jawaid
 * License: GPL v3 or later
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit; // Exit if accessed directly
}

// Add admin menu
function ecopower_tracker_menu() {
    add_menu_page(
        'EcoPower Tracker',
        'EcoPower Tracker',
        'manage_options',
        'ecopower-tracker',
        'ecopower_tracker_admin_page',
        'dashicons-admin-site',
        6
    );

    add_submenu_page(
        'ecopower-tracker',
        'Project Data',
        'Project Data',
        'manage_options',
        'ecopower-tracker-data',
        'ecopower_tracker_data_page'
    );
}
add_action( 'admin_menu', 'ecopower_tracker_menu' );

// Admin page content
function ecopower_tracker_admin_page() {
    include plugin_dir_path( __FILE__ ) . 'form.php';
}

// Data page content
function ecopower_tracker_data_page() {
    include plugin_dir_path( __FILE__ ) . 'data.php';
}

// Include other required files
require_once plugin_dir_path( __FILE__ ) . 'includes/settings.php';
require_once plugin_dir_path( __FILE__ ) . 'includes/sanitization.php';

// Calculation functions
function calculate_total_power_generated($projects) {
    $total_power = 0;
    foreach ($projects as $project) {
        $date_of_activation = new DateTime($project['date_of_activation']);
        $now = new DateTime();
        $days_active = $now->diff($date_of_activation)->days;
        $annual_generation = $project['generation_capacity'] * $project['project_cuf'] * 24 * 365;
        $daily_generation = $annual_generation / 365;
        $total_power += $daily_generation * $days_active;
    }
    return $total_power;
}

function calculate_carbon_offset($total_power) {
    $carbon_offset_per_kwh = 0.92; // Example conversion factor, can be adjusted
    return $total_power * $carbon_offset_per_kwh;
}

// Shortcodes
function ecopower_tracker_shortcode() {
    $options = get_option( 'ecopower_tracker_options' );
    if ( empty( $options ) ) {
        return 'No project data available.';
    }
    $projects = array($options); // Assuming $options contains project data

    $total_power_generated = calculate_total_power_generated($projects);
    $total_carbon_offset = calculate_carbon_offset($total_power_generated);

    $output = '<div>Total Power Generated: ' . number_format($total_power_generated, 2) . ' kWh</div>';
    $output .= '<div>Total Carbon Offset: ' . number_format($total_carbon_offset, 2) . ' kg CO2</div>';
    return $output;
}
add_shortcode( 'ecopower_tracker', 'ecopower_tracker_shortcode' );
?>
