<?php
/**
 * Plugin Name: EcoPower Tracker
 * Description: Calculates and displays total power generated by wind and solar plants in real-time, along with the carbon offset generated.
 * Version: 1.0
 * Author: Saqib Jawaid
 * License: GPL v3 or later
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit; // Exit if accessed directly
}

// Add admin menu
function ecopower_tracker_menu() {
    add_menu_page(
        'EcoPower Tracker',
        'EcoPower Tracker',
        'manage_options',
        'ecopower-tracker',
        'ecopower_tracker_admin_page',
        'dashicons-admin-site',
        6
    );
}
add_action( 'admin_menu', 'ecopower_tracker_menu' );

// Admin page content
function ecopower_tracker_admin_page() {
    include plugin_dir_path( __FILE__ ) . 'form.php';
}

// Include other required files
require_once plugin_dir_path( __FILE__ ) . 'includes/settings.php';
require_once plugin_dir_path( __FILE__ ) . 'includes/sanitization.php';

// Shortcodes
function ecopower_tracker_shortcode() {
    $options = get_option( 'ecopower_tracker_options' );
    if ( empty( $options ) ) {
        return 'No project data available.';
    }
    // Your calculations and output formatting here
    // Example:
    $output = '<div>Total Power Generated: ...</div>';
    $output .= '<div>Total Carbon Offset: ...</div>';
    return $output;
}
add_shortcode( 'ecopower_tracker', 'ecopower_tracker_shortcode' );
?>
