// Path: EcoPower-Tracker/templates/admin/about.php
// File: about.php

<?php

if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly
}

// Include necessary utility functions if any

?>

<div class="wrap">
    <h1><?php _e('About EcoPower Tracker', 'ecopower-tracker'); ?></h1>

    <div class="ecopower-tracker-about">
        <p><?php _e('EcoPower Tracker is a comprehensive plugin designed to manage and display data from renewable energy projects, focusing on solar and wind energy. The plugin helps track power generation and CO2 offset.', 'ecopower-tracker'); ?></p>

        <h2><?php _e('Shortcodes', 'ecopower-tracker'); ?></h2>
        <p><?php _e('You can use the following shortcodes to display various data views on your site:', 'ecopower-tracker'); ?></p>
        <ul>
            <li><code>[ecopower_tracker_total_power]</code> - <?php _e('Displays the total power generated by all projects combined.', 'ecopower-tracker'); ?></li>
            <li><code>[ecopower_tracker_total_co2]</code> - <?php _e('Displays the total CO2 offset by all projects combined.', 'ecopower-tracker'); ?></li>
            <li><code>[ecopower_tracker_project_power project_id="X"]</code> - <?php _e('Displays the power generated by a specific project, identified by its ID.', 'ecopower-tracker'); ?></li>
            <li><code>[ecopower_tracker_project_co2 project_id="X"]</code> - <?php _e('Displays the CO2 offset by a specific project, identified by its ID.', 'ecopower-tracker'); ?></li>
            <li><code>[ecopower_tracker_project_capacity project_id="X"]</code> - <?php _e('Displays the generation capacity of a specific project, identified by its ID.', 'ecopower-tracker'); ?></li>
            <li><code>[ecopower_tracker_company_power company="Company Name"]</code> - <?php _e('Displays the total power generated by all projects from a specific company.', 'ecopower-tracker'); ?></li>
            <li><code>[ecopower_tracker_company_co2 company="Company Name"]</code> - <?php _e('Displays the total CO2 offset by all projects from a specific company.', 'ecopower-tracker'); ?></li>
            <li><code>[ecopower_tracker_company_capacity company="Company Name"]</code> - <?php _e('Displays the total generation capacity of all projects from a specific company.', 'ecopower-tracker'); ?></li>
            <li><code>[ecopower_tracker_location_power location="Location"]</code> - <?php _e('Displays the total power generated by all projects in a specific location.', 'ecopower-tracker'); ?></li>
            <li><code>[ecopower_tracker_location_co2 location="Location"]</code> - <?php _e('Displays the total CO2 offset by all projects in a specific location.', 'ecopower-tracker'); ?></li>
            <li><code>[ecopower_tracker_location_capacity location="Location"]</code> - <?php _e('Displays the total generation capacity of all projects in a specific location.', 'ecopower-tracker'); ?></li>
            <li><code>[ecopower_tracker_type_power type="Type"]</code> - <?php _e('Displays the total power generated by all projects of a specific type (Wind or Solar).', 'ecopower-tracker'); ?></li>
            <li><code>[ecopower_tracker_type_co2 type="Type"]</code> - <?php _e('Displays the total CO2 offset by all projects of a specific type (Wind or Solar).', 'ecopower-tracker'); ?></li>
            <li><code>[ecopower_tracker_type_capacity type="Type"]</code> - <?php _e('Displays the total generation capacity of all projects of a specific type (Wind or Solar).', 'ecopower-tracker'); ?></li>
        </ul>

        <h2><?php _e('Usage Manual', 'ecopower-tracker'); ?></h2>
        <p><?php _e('To use EcoPower Tracker, follow these steps:', 'ecopower-tracker'); ?></p>
        <ol>
            <li><?php _e('Install and activate the plugin from the WordPress plugin repository.', 'ecopower-tracker'); ?></li>
            <li><?php _e('Navigate to the EcoPower Tracker menu in the admin dashboard.', 'ecopower-tracker'); ?></li>
            <li><?php _e('Use the dashboard to upload project data via CSV, view existing projects, and export data.', 'ecopower-tracker'); ?></li>
            <li><?php _e('Use the provided shortcodes to display data on your site. Refer to the shortcode list above for details.', 'ecopower-tracker'); ?></li>
        </ol>

        <h2><?php _e('Support', 'ecopower-tracker'); ?></h2>
        <p><?php _e('For support and to report issues, visit our ', 'ecopower-tracker'); ?><a href="https://github.com/saqibj/EcoTracker" target="_blank"><?php _e('GitHub page', 'ecopower-tracker'); ?></a>.</p>
    </div>
</div>

<style>
    .ecopower-tracker-about {
        margin-top: 20px;
        padding: 20px;
        border: 1px solid #ddd;
        background-color: #f9f9f9;
        border-radius: 5px;
    }

    .ecopower-tracker-about h2 {
        margin-top: 20px;
        font-size: 1.5em;
    }

    .ecopower-tracker-about ul {
        list-style-type: disc;
        margin-left: 20px;
    }

    .ecopower-tracker-about ol {
        list-style-type: decimal;
        margin-left: 20px;
    }

    .ecopower-tracker-about a {
        color: #0073aa;
        text-decoration: none;
    }

    .ecopower-tracker-about a:hover {
        text-decoration: underline;
    }
</style>

<?php
?>