<?php
if ( ! defined( 'ABSPATH' ) ) {
    exit; // Exit if accessed directly.
}

// Function to display the About page with a detailed usage manual
function ecopower_tracker_about_page() {
    echo '<div class="wrap">';
    echo '<h1>' . __( 'About EcoPower Tracker', 'ecopower-tracker' ) . '</h1>';
    echo '<div style="text-align: center; margin-bottom: 20px;"><img src="' . plugin_dir_url( __FILE__ ) . '../img/EcoTracker-Logo.webp" style="max-width: 20%;" alt="EcoPower Tracker Logo" /></div>';
    echo '<p>' . __( 'Version 2.1e', 'ecopower-tracker' ) . '</p>';
    echo '<p>' . __( 'EcoPower Tracker helps you manage and display renewable energy project data, including total power generation, CO2 offset, and generation capacity.', 'ecopower-tracker' ) . '</p>';

    echo '<h2>' . __( 'Usage Manual', 'ecopower-tracker' ) . '</h2>';

    // General Usage Instructions
    echo '<h3>' . __( 'General Instructions', 'ecopower-tracker' ) . '</h3>';
    echo '<p>' . __( 'To use the EcoPower Tracker plugin, you can add shortcodes to any page or post to display specific data about your renewable energy projects.', 'ecopower-tracker' ) . '</p>';
    echo '<p>' . __( 'Here are the available shortcodes and how to use them:', 'ecopower-tracker' ) . '</p>';

    // Shortcodes List
    echo '<h3>' . __( 'Available Shortcodes', 'ecopower-tracker' ) . '</h3>';

    echo '<h4>' . __( '1. Total Power Generated', 'ecopower-tracker' ) . '</h4>';
    echo '<p>' . __( 'Displays the total power generated by all projects.', 'ecopower-tracker' ) . '</p>';
    echo '<p><code>[ecopower_tracker_total_power]</code></p>';

    echo '<h4>' . __( '2. Total CO2 Offset', 'ecopower-tracker' ) . '</h4>';
    echo '<p>' . __( 'Displays the total CO2 offset by all projects.', 'ecopower-tracker' ) . '</p>';
    echo '<p><code>[ecopower_tracker_total_co2]</code></p>';

    echo '<h4>' . __( '3. All Projects Table', 'ecopower-tracker' ) . '</h4>';
    echo '<p>' . __( 'Displays a table listing all projects with their details.', 'ecopower-tracker' ) . '</p>';
    echo '<p><code>[ecopower_tracker_projects]</code></p>';

    echo '<h4>' . __( '4. Total Power Generated (Number Only)', 'ecopower-tracker' ) . '</h4>';
    echo '<p>' . __( 'Displays the total power generated as a plain number.', 'ecopower-tracker' ) . '</p>';
    echo '<p><code>[ecopower_tracker_total_power_number]</code></p>';

    echo '<h4>' . __( '5. Total CO2 Offset (Number Only)', 'ecopower-tracker' ) . '</h4>';
    echo '<p>' . __( 'Displays the total CO2 offset as a plain number.', 'ecopower-tracker' ) . '</p>';
    echo '<p><code>[ecopower_tracker_total_co2_number]</code></p>';

    echo '<h4>' . __( '6. Specific Project Details', 'ecopower-tracker' ) . '</h4>';
    echo '<p>' . __( 'Displays details for a specific project.', 'ecopower-tracker' ) . '</p>';
    echo '<p><code>[ecopower_tracker_project project_name="Project Name"]</code></p>';
    echo '<p>' . __( 'Example:', 'ecopower-tracker' ) . ' <code>[ecopower_tracker_project project_name="Solar Plant 1"]</code></p>';

    echo '<h4>' . __( '7. Grouped by Company', 'ecopower-tracker' ) . '</h4>';
    echo '<p>' . __( 'Displays aggregated data for all projects under a specific company.', 'ecopower-tracker' ) . '</p>';
    echo '<p><code>[ecopower_tracker_company company_name="Company Name"]</code></p>';
    echo '<p>' . __( 'Example:', 'ecopower-tracker' ) . ' <code>[ecopower_tracker_company company_name="Solar Corp"]</code></p>';

    echo '<h4>' . __( '8. Grouped by Location', 'ecopower-tracker' ) . '</h4>';
    echo '<p>' . __( 'Displays aggregated data for all projects at a specific location.', 'ecopower-tracker' ) . '</p>';
    echo '<p><code>[ecopower_tracker_location location="Location Name"]</code></p>';
    echo '<p>' . __( 'Example:', 'ecopower-tracker' ) . ' <code>[ecopower_tracker_location location="Location 1"]</code></p>';

    echo '<h4>' . __( '9. Grouped by Type of Plant', 'ecopower-tracker' ) . '</h4>';
    echo '<p>' . __( 'Displays aggregated data for all projects of a specific type.', 'ecopower-tracker' ) . '</p>';
    echo '<p><code>[ecopower_tracker_type plant_type="Plant Type"]</code></p>';
    echo '<p>' . __( 'Example:', 'ecopower-tracker' ) . ' <code>[ecopower_tracker_type plant_type="Solar"]</code></p>';

    echo '<h4>' . __( '10. Total Generation Capacity', 'ecopower-tracker' ) . '</h4>';
    echo '<p>' . __( 'Displays the total generation capacity of all projects combined.', 'ecopower-tracker' ) . '</p>';
    echo '<p><code>[ecopower_tracker_total_capacity]</code></p>';

    echo '<h4>' . __( '11. Generation Capacity for a Specific Project', 'ecopower-tracker' ) . '</h4>';
    echo '<p>' . __( 'Displays the generation capacity for a specified project.', 'ecopower-tracker' ) . '</p>';
    echo '<p><code>[ecopower_tracker_project_capacity project_name="Project Name"]</code></p>';
    echo '<p>' . __( 'Example:', 'ecopower-tracker' ) . ' <code>[ecopower_tracker_project_capacity project_name="Solar Plant 1"]</code></p>';

    echo '<h4>' . __( '12. Total Generation Capacity Grouped by Company', 'ecopower-tracker' ) . '</h4>';
    echo '<p>' . __( 'Displays the total generation capacity for all projects under a specified company.', 'ecopower-tracker' ) . '</p>';
    echo '<p><code>[ecopower_tracker_company_capacity company_name="Company Name"]</code></p>';
    echo '<p>' . __( 'Example:', 'ecopower-tracker' ) . ' <code>[ecopower_tracker_company_capacity company_name="Solar Corp"]</code></p>';

    echo '<h4>' . __( '13. Total Generation Capacity Grouped by Location', 'ecopower-tracker' ) . '</h4>';
    echo '<p>' . __( 'Displays the total generation capacity for all projects at a specified location.', 'ecopower-tracker' ) . '</p>';
    echo '<p><code>[ecopower_tracker_location_capacity location="Location Name"]</code></p>';
    echo '<p>' . __( 'Example:', 'ecopower-tracker' ) . ' <code>[ecopower_tracker_location_capacity location="Location 1"]</code></p>';

    echo '<h4>' . __( '14. Total Generation Capacity Grouped by Type of Plant', 'ecopower-tracker' ) . '</h4>';
    echo '<p>' . __( 'Displays the total generation capacity for all projects of a specified type.', 'ecopower-tracker' ) . '</p>';
    echo '<p><code>[ecopower_tracker_type_capacity plant_type="Plant Type"]</code></p>';
    echo '<p>' . __( 'Example:', 'ecopower-tracker' ) . ' <code>[ecopower_tracker_type_capacity plant_type="Solar"]</code></p>';

    // Import/Export Instructions
    echo '<h3>' . __( 'CSV Import/Export Instructions', 'ecopower-tracker' ) . '</h3>';
    echo '<p>' . __( 'You can import and export project data using a CSV file. The required columns are as follows:', 'ecopower-tracker' ) . '</p>';

    echo '<table class="widefat">';
    echo '<thead><tr><th>' . __( 'Column Name', 'ecopower-tracker' ) . '</th><th>' . __( 'Description', 'ecopower-tracker' ) . '</th></tr></thead>';
    echo '<tbody>';
    echo '<tr><td>' . __( 'Project Company', 'ecopower-tracker' ) . '</td><td>' . __( 'Name of the company that owns the project.', 'ecopower-tracker' ) . '</td></tr>';
    echo '<tr><td>' . __( 'Project Name', 'ecopower-tracker' ) . '</td><td>' . __( 'Name of the project.', 'ecopower-tracker' ) . '</td></tr>';
    echo '<tr><td>' . __( 'Project Location', 'ecopower-tracker' ) . '</td><td>' . __( 'Location of the project.', 'ecopower-tracker' ) . '</td></tr>';
    echo '<tr><td>' . __( 'Type of Plant', 'ecopower-tracker' ) . '</td><td>' . __( 'Type of the plant (e.g., Solar, Wind).', 'ecopower-tracker' ) . '</td></tr>';
    echo '<tr><td>' . __( 'Project CUF', 'ecopower-tracker' ) . '</td><td>' . __( 'Capacity Utilization Factor of the project.', 'ecopower-tracker' ) . '</td></tr>';
    echo '<tr><td>' . __( 'Generation Capacity (KW)', 'ecopower-tracker' ) . '</td><td>' . __( 'Generation capacity of the project in KW.', 'ecopower-tracker' ) . '</td></tr>';
    echo '<tr><td>' . __( 'Date of Activation', 'ecopower-tracker' ) . '</td><td>' . __( 'Date when the project was activated (YYYY-MM-DD).', 'ecopower-tracker' ) . '</td></tr>';
    echo '</tbody>';
    echo '</table>';

    echo '<p>' . __( 'Ensure that your CSV file matches the above format for a successful import.', 'ecopower-tracker' ) . '</p>';

    // Support and Links
    echo '<h3>' . __( 'Support and Links', 'ecopower-tracker' ) . '</h3>';
    echo '<p>' . __( 'For support, visit our GitHub page:', 'ecopower-tracker' ) . ' <a href="https://github.com/saqibj/EcoTracker" target="_blank">EcoPower Tracker on GitHub</a>.</p>';
    echo '<p>' . __( 'To report issues or request features, open an issue on our GitHub Issues page:', 'ecopower-tracker' ) . ' <a href="https://github.com/saqibj/EcoTracker/issues" target="_blank">GitHub Issues</a>.</p>';

    echo '</div>';
}
?>