<?php
if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly
}

// Register shortcodes
function ecopower_tracker_register_shortcodes() {
    add_shortcode('ecopower_total_power_generated', 'ecopower_total_power_generated');
    add_shortcode('ecopower_total_carbon_offset', 'ecopower_total_carbon_offset');
    add_shortcode('ecopower_project_power_generated', 'ecopower_project_power_generated');
    add_shortcode('ecopower_project_carbon_offset', 'ecopower_project_carbon_offset');
    add_shortcode('ecopower_subgroup_power_generated', 'ecopower_subgroup_power_generated');
    add_shortcode('ecopower_subgroup_carbon_offset', 'ecopower_subgroup_carbon_offset');
}
add_action('init', 'ecopower_tracker_register_shortcodes');

// Calculate total power generated
function ecopower_total_power_generated($atts) {
    global $wpdb;
    $table_name = $wpdb->prefix . 'ecopower_projects';

    $total_power_generated = $wpdb->get_var("SELECT SUM(generation_capacity) FROM $table_name");
    $total_power_generated = number_format($total_power_generated);

    return '<div class="ecopower-total-power-generated">' . sprintf(__('Total Power Generated: %s KWh', 'ecopower-tracker'), $total_power_generated) . '</div>';
}

// Calculate total carbon offset
function ecopower_total_carbon_offset($atts) {
    global $wpdb;
    $table_name = $wpdb->prefix . 'ecopower_projects';

    $total_power_generated = $wpdb->get_var("SELECT SUM(generation_capacity) FROM $table_name");
    $carbon_offset = $total_power_generated * 0.85; // Example conversion factor
    $carbon_offset = number_format($carbon_offset);

    return '<div class="ecopower-total-carbon-offset">' . sprintf(__('Total Carbon Offset: %s kg CO2', 'ecopower-tracker'), $carbon_offset) . '</div>';
}

// Calculate power generated by individual project
function ecopower_project_power_generated($atts) {
    global $wpdb;
    $table_name = $wpdb->prefix . 'ecopower_projects';

    $atts = shortcode_atts(array('project_id' => ''), $atts, 'ecopower_project_power_generated');
    $project_id = intval($atts['project_id']);

    $project_power_generated = $wpdb->get_var($wpdb->prepare("SELECT generation_capacity FROM $table_name WHERE id = %d", $project_id));
    $project_power_generated = number_format($project_power_generated);

    return '<div class="ecopower-project-power-generated">' . sprintf(__('Project Power Generated: %s KWh', 'ecopower-tracker'), $project_power_generated) . '</div>';
}

// Calculate carbon offset by individual project
function ecopower_project_carbon_offset($atts) {
    global $wpdb;
    $table_name = $wpdb->prefix . 'ecopower_projects';

    $atts = shortcode_atts(array('project_id' => ''), $atts, 'ecopower_project_carbon_offset');
    $project_id = intval($atts['project_id']);

    $project_power_generated = $wpdb->get_var($wpdb->prepare("SELECT generation_capacity FROM $table_name WHERE id = %d", $project_id));
    $carbon_offset = $project_power_generated * 0.85; // Example conversion factor
    $carbon_offset = number_format($carbon_offset);

    return '<div class="ecopower-project-carbon-offset">' . sprintf(__('Project Carbon Offset: %s kg CO2', 'ecopower-tracker'), $carbon_offset) . '</div>';
}

// Calculate power generated by subgroup of projects
function ecopower_subgroup_power_generated($atts) {
    global $wpdb;
    $table_name = $wpdb->prefix . 'ecopower_projects';

    $atts = shortcode_atts(array('project_ids' => ''), $atts, 'ecopower_subgroup_power_generated');
    $project_ids = array_map('intval', explode(',', $atts['project_ids']));
    $project_ids_placeholder = implode(',', array_fill(0, count($project_ids), '%d'));

    $subgroup_power_generated = $wpdb->get_var($wpdb->prepare("SELECT SUM(generation_capacity) FROM $table_name WHERE id IN ($project_ids_placeholder)", $project_ids));
    $subgroup_power_generated = number_format($subgroup_power_generated);

    return '<div class="ecopower-subgroup-power-generated">' . sprintf(__('Subgroup Power Generated: %s KWh', 'ecopower-tracker'), $subgroup_power_generated) . '</div>';
}

// Calculate carbon offset by subgroup of projects
function ecopower_subgroup_carbon_offset($atts) {
    global $wpdb;
    $table_name = $wpdb->prefix . 'ecopower_projects';

    $atts = shortcode_atts(array('project_ids' => ''), $atts, 'ecopower_subgroup_carbon_offset');
    $project_ids = array_map('intval', explode(',', $atts['project_ids']));
    $project_ids_placeholder = implode(',', array_fill(0, count($project_ids), '%d'));

    $subgroup_power_generated = $wpdb->get_var($wpdb->prepare("SELECT SUM(generation_capacity) FROM $table_name WHERE id IN ($project_ids_placeholder)", $project_ids));
    $carbon_offset = $subgroup_power_generated * 0.85; // Example conversion factor
    $carbon_offset = number_format($carbon_offset);

    return '<div class="ecopower-subgroup-carbon-offset">' . sprintf(__('Subgroup Carbon Offset: %s kg CO2', 'ecopower-tracker'), $carbon_offset) . '</div>';
}
?>